# Generated by Django 3.1.1 on 2020-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_event_eventmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
