# Generated by Django 3.1.1 on 2020-11-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_eventmember_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='user',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together=set(),
        ),
    ]
