# Generated by Django 3.1.1 on 2020-11-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20201119_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='email',
        ),
    ]
