# Generated by Django 3.1.1 on 2020-11-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_eventmember_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmember',
            name='user',
        ),
        migrations.AddField(
            model_name='eventmember',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
