# Generated by Django 3.1.1 on 2020-11-22 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_eventoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoptions',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='eventoptions',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='first_app.event'),
        ),
    ]
