# Generated by Django 3.1.1 on 2020-11-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20201122_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOptions_attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(default='', max_length=20)),
                ('event_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='first_app.eventoptions')),
            ],
        ),
    ]
