# Generated by Django 3.1.1 on 2020-11-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_eventoptions_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoptions_attendee',
            name='attendee_name',
        ),
        migrations.AddField(
            model_name='eventoptions_attendee',
            name='attendee_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee_email', to='first_app.eventmember'),
        ),
    ]
